apiVersion: v1
kind: ReplicationController
metadata:
  name: sickrage
  labels:
    name: sickrage
spec:
  replicas: 1
  selector:
    name: sickrage
  template:
    metadata:
      labels:
        name: sickrage
    spec:
      containers:
      - name: sickrage
        image: brujoand/rpi-sickrage
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
          hostPort: 8081
          name: http-sickrage
        volumeMounts:
        - name: nfs-data
          mountPath: /data
        - name: nfs-config
          mountPath: /config
      volumes:
        - name: nfs-data
          persistentVolumeClaim:
            claimName: nfs-data
        - name: nfs-config
          persistentVolumeClaim:
            claimName: nfs-config
