apiVersion: v1
kind: Service
metadata:
  name: sickrage
  labels:
    name: sickrage
  annotations:
    virtual_host: "sick.brujordet.no"
    virtual_port: "8081"
spec:
  ports:
    - port: 8081
  selector:
    name: sickrage
  type: ClusterIP
