apiVersion: v1
kind: Service
metadata:
  name: transmission
  labels:
    name: transmission
  annotations:
    virtual_host: "trans.brujordet.no"
    virtual_port: "9091"
spec:
  ports:
    - port: 9091
  selector:
    name: transmission
  type: ClusterIP
