apiVersion: v1
kind: ReplicationController
metadata:
  name: transmission
  labels:
    name: transmission
spec:
  replicas: 1
  selector:
    name: transmission
  template:
    metadata:
      labels:
        name: transmission
    spec:
      containers:
      - name: transmission
        image: brujoand/rpi-transmission
        imagePullPolicy: Always
        ports:
        - containerPort: 9091
          hostPort: 9091
          name: http-trans
        volumeMounts:
        - name: nfs-data
          mountPath: /data
        - name: nfs-config
          mountPath: /config
      volumes:
        - name: nfs-data
          persistentVolumeClaim:
            claimName: nfs-data
        - name: nfs-config
          persistentVolumeClaim:
            claimName: nfs-config
