apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-config
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.1.2
    path: "/Users/brujoand/config"
