apiVersion: v1
kind: ReplicationController
metadata:
  name: nzbget
  labels:
    name: nzbget
spec:
  replicas: 1
  selector:
    name: nzbget
  template:
    metadata:
      labels:
        name: nzbget
    spec:
      containers:
      - name: nzbget
        image: brujoand/rpi-nzbget
        imagePullPolicy: Always
        ports:
        - containerPort: 6789
          hostPort: 6789
          name: http-nzbget
        volumeMounts:
        - name: nfs-data
          mountPath: /data
        - name: nfs-config
          mountPath: /config
        - name: usbdisk
          mountPath: /usbdisk
      volumes:
        - name: nfs-data
          persistentVolumeClaim:
            claimName: nfs-data
        - name: nfs-config
          persistentVolumeClaim:
            claimName: nfs-config
        - name: usbdisk
          persistentVolumeClaim:
            claimName: usbdisk
      nodeSelector:
        usbdisk: 'true'

