apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  replicas: 1
  selector:
    name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - name: nginx
        env:
          - name: ETCD_IP
            value: 10.0.1.36
        image: brujoand/rpi-nginx
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          hostPort: 80
          name: http-nginx
