apiVersion: v1
kind: Service
metadata:
  name: couchpotato
  labels:
    name: couchpotato
  annotations:
    virtual_host: "couch.brujordet.no"
    virtual_port: "5050"
spec:
  ports:
    - port: 5050
  selector:
    name: couchpotato
  type: ClusterIP
