apiVersion: v1
kind: Service
metadata:
  name: droneio
  labels:
    name: droneio
  annotations:
    virtual_host: "drone.brujordet.no"
    virtual_port: "80"
spec:
  ports:
    - port: 80
  selector:
    name: droneio
  type: ClusterIP
