apiVersion: v1
kind: ReplicationController
metadata:
  name: droneio
  labels:
    name: droneio
spec:
  replicas: 1
  selector:
    name: droneio
  template:
    metadata:
      labels:
        name: droneio
    spec:
      containers:
        - image: armhfbuild/drone
          name: droneio
          env:
            # HTTP Listen Address
            - name: SERVER_ADDR
              value: ":80"
            - name: DATABASE_DRIVER
              value: sqlite3
            - name: DATABASE_CONFIG
              value: /var/lib/drone/drone.sqlite
            - name: REMOTE_DRIVER
              value: github
            - name: REMOTE_CONFIG
              value: https://github.com?client_id=${github_client_id}&client_secret=${github_client_secret} 
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/drone
              name: nfs-config
            - mountPath: /var/run/docker.sock
              name: docker-socket
            - mountPath: /var/lib/docker
              name: docker-lib
      volumes:
        - name: nfs-config
          persistentVolumeClaim:
            claimName: nfs-config
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: docker-lib
          hostPath:
            path: /var/lib/docker
